sugarcube-2:
  macros:
    disable:
      name: disable
      container: true
    IfAntony:
      name: IfAntony
    send:
      name: send
      container: true
    receive:
      name: receive
      container: true
    connect:
      name: connect
    preprocessreceivetags:
      name: preprocessreceivetags
    managesavesonpassageready:
      name: managesavesonpassageready
    endmultiplayergame:
      name: endmultiplayergame
